require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CurliesController do

  # This should return the minimal set of attributes required to create a valid
  # Curly. As you add validations to Curly, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CurliesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all curlies as @curlies" do
      curly = Curly.create! valid_attributes
      get :index, {}, valid_session
      assigns(:curlies).should eq([curly])
    end
  end

  describe "GET show" do
    it "assigns the requested curly as @curly" do
      curly = Curly.create! valid_attributes
      get :show, {:id => curly.to_param}, valid_session
      assigns(:curly).should eq(curly)
    end
  end

  describe "GET new" do
    it "assigns a new curly as @curly" do
      get :new, {}, valid_session
      assigns(:curly).should be_a_new(Curly)
    end
  end

  describe "GET edit" do
    it "assigns the requested curly as @curly" do
      curly = Curly.create! valid_attributes
      get :edit, {:id => curly.to_param}, valid_session
      assigns(:curly).should eq(curly)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Curly" do
        expect {
          post :create, {:curly => valid_attributes}, valid_session
        }.to change(Curly, :count).by(1)
      end

      it "assigns a newly created curly as @curly" do
        post :create, {:curly => valid_attributes}, valid_session
        assigns(:curly).should be_a(Curly)
        assigns(:curly).should be_persisted
      end

      it "redirects to the created curly" do
        post :create, {:curly => valid_attributes}, valid_session
        response.should redirect_to(Curly.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved curly as @curly" do
        # Trigger the behavior that occurs when invalid params are submitted
        Curly.any_instance.stub(:save).and_return(false)
        post :create, {:curly => {  }}, valid_session
        assigns(:curly).should be_a_new(Curly)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Curly.any_instance.stub(:save).and_return(false)
        post :create, {:curly => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested curly" do
        curly = Curly.create! valid_attributes
        # Assuming there are no other curlies in the database, this
        # specifies that the Curly created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Curly.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => curly.to_param, :curly => { "these" => "params" }}, valid_session
      end

      it "assigns the requested curly as @curly" do
        curly = Curly.create! valid_attributes
        put :update, {:id => curly.to_param, :curly => valid_attributes}, valid_session
        assigns(:curly).should eq(curly)
      end

      it "redirects to the curly" do
        curly = Curly.create! valid_attributes
        put :update, {:id => curly.to_param, :curly => valid_attributes}, valid_session
        response.should redirect_to(curly)
      end
    end

    describe "with invalid params" do
      it "assigns the curly as @curly" do
        curly = Curly.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Curly.any_instance.stub(:save).and_return(false)
        put :update, {:id => curly.to_param, :curly => {  }}, valid_session
        assigns(:curly).should eq(curly)
      end

      it "re-renders the 'edit' template" do
        curly = Curly.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Curly.any_instance.stub(:save).and_return(false)
        put :update, {:id => curly.to_param, :curly => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested curly" do
      curly = Curly.create! valid_attributes
      expect {
        delete :destroy, {:id => curly.to_param}, valid_session
      }.to change(Curly, :count).by(-1)
    end

    it "redirects to the curlies list" do
      curly = Curly.create! valid_attributes
      delete :destroy, {:id => curly.to_param}, valid_session
      response.should redirect_to(curlies_url)
    end
  end

end
